

services:

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - /root/cht-docs-old:/home/cht-docs-old
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cht-watchdog-net

volumes:
  caddy_data:
  caddy_config:

networks:
  cht-watchdog-net:
    external: true
